name: base_env # Use your own env name
channels:
  - conda-forge
  - defaults
dependencies:
  - alembic=1.8.0=pyhd8ed1ab_0
  - anyio=4.2.0=py311hca03da5_0
  - aom=3.6.0=h313beb8_0
  - appnope=0.1.2=py311hca03da5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h80987f9_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py311hca03da5_0
  - attrs=23.1.0=py311hca03da5_0
  - babel=2.11.0=py311hca03da5_0
  - beautifulsoup4=4.12.2=py311hca03da5_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.3=h313beb8_0
  - bottleneck=1.3.7=py311hb9f6ed7_0
  - brotli=1.0.9=h80987f9_8
  - brotli-bin=1.0.9=h80987f9_8
  - brotli-python=1.0.9=py311h313beb8_8
  - brunsli=0.1=hc377ac9_1
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.16.0=h302bd0f_5
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.16.0=py311h80987f9_1
  - cfitsio=3.470=h7f6438f_7
  - charls=2.2.0=hc377ac9_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=py311hca03da5_0
  - colorlog=6.9.0=pyh707e725_1
  - comm=0.2.1=py311hca03da5_0
  - contourpy=1.2.0=py311h48ca7d4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h9131b1a_1
  - cython=3.0.11=py311h80987f9_1
  - dav1d=1.2.1=h80987f9_0
  - debugpy=1.6.7=py311h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - docutils=0.18.1=py311hca03da5_3
  - eigen=3.4.0=h48ca7d4_0
  - et_xmlfile=1.1.0=py311hca03da5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.2=h313beb8_0
  - ffmpeg=4.2.2=h04105a8_0
  - filelock=3.13.1=py311hca03da5_0
  - fontconfig=2.14.1=hee714a5_2
  - fonttools=4.51.0=py311h80987f9_0
  - freetype=2.12.1=h1192e45_0
  - fsspec=2024.3.1=py311hca03da5_0
  - gettext=0.21.0=h13f89a0_1
  - giflib=5.2.1=h80987f9_3
  - glib=2.78.4=h313beb8_0
  - glib-tools=2.78.4=h313beb8_0
  - gmp=6.2.1=hc377ac9_3
  - gmpy2=2.1.2=py311h40f64dc_0
  - gnutls=3.6.15=h887c41c_0
  - graphite2=1.3.14=hc377ac9_1
  - greenlet=3.1.1=py311h313beb8_0
  - gst-plugins-base=1.14.1=h313beb8_1
  - gstreamer=1.14.1=h80987f9_1
  - harfbuzz=4.3.0=he9eebac_1
  - hdf5=1.12.1=h05c076b_3
  - icu=68.1=hc377ac9_0
  - idna=3.7=py311hca03da5_0
  - imagecodecs=2023.1.23=py311h5e7c512_0
  - imageio=2.33.1=py311hca03da5_0
  - imagesize=1.4.1=py311hca03da5_0
  - imbalanced-learn=0.11.0=py311hca03da5_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.28.0=py311hca03da5_0
  - jedi=0.18.1=py311hca03da5_1
  - jinja2=3.1.4=py311hca03da5_0
  - joblib=1.4.0=py311hca03da5_0
  - jpeg=9e=h80987f9_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py311hca03da5_0
  - jsonschema-specifications=2023.7.1=py311hca03da5_0
  - jupyter-lsp=2.2.0=py311hca03da5_0
  - jupyter_client=8.6.0=py311hca03da5_0
  - jupyter_core=5.5.0=py311hca03da5_0
  - jupyter_events=0.8.0=py311hca03da5_0
  - jupyter_server=2.10.0=py311hca03da5_0
  - jupyter_server_terminals=0.4.4=py311hca03da5_1
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.25.1=py311hca03da5_0
  - jxrlib=1.1=h1a28f6b_2
  - kiwisolver=1.4.4=py311h313beb8_0
  - krb5=1.20.1=hf3e1bf2_1
  - lame=3.100=h1a28f6b_0
  - lazy_loader=0.3=py311hca03da5_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libaec=1.0.4=hc377ac9_1
  - libavif=0.11.1=h80987f9_0
  - libbrotlicommon=1.0.9=h80987f9_8
  - libbrotlidec=1.0.9=h80987f9_8
  - libbrotlienc=1.0.9=h80987f9_8
  - libclang=14.0.6=default_h1b80db6_1
  - libclang13=14.0.6=default_h24352ff_1
  - libcurl=8.7.1=h3e2b118_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.78.4=h0a96307_0
  - libiconv=1.16=h80987f9_3
  - libidn2=2.3.4=h80987f9_0
  - libllvm14=14.0.6=h7ec7a93_3
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.21=h269037a_0
  - libopus=1.3=h1a28f6b_1
  - libpng=1.6.39=h80987f9_0
  - libpq=12.17=h02f6b3c_0
  - libprotobuf=3.20.3=h514c7bf_0
  - libsodium=1.0.18=h1a28f6b_0
  - libssh2=1.11.0=h3e2b118_0
  - libtasn1=4.19.0=h80987f9_0
  - libtiff=4.5.1=h313beb8_0
  - libunistring=0.9.10=h1a28f6b_0
  - libuv=1.44.2=h80987f9_0
  - libvpx=1.10.0=hc377ac9_0
  - libwebp=1.3.2=ha3663a8_0
  - libwebp-base=1.3.2=h80987f9_0
  - libxml2=2.10.4=h372ba2a_0
  - libxslt=1.1.37=habca612_0
  - libzopfli=1.0.3=hc377ac9_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - mako=1.3.10=pyhd8ed1ab_0
  - markupsafe=2.1.3=py311h80987f9_0
  - matplotlib-base=3.8.0=py311h7aedaa7_0
  - matplotlib-inline=0.1.6=py311hca03da5_0
  - mistune=2.0.4=py311hca03da5_0
  - mpc=1.1.0=h8c48613_1
  - mpfr=4.0.2=h695f6f0_1
  - mpmath=1.3.0=py311hca03da5_0
  - mysql=5.7.24=ha71a6ea_2
  - nbclient=0.8.0=py311hca03da5_0
  - nbconvert=7.10.0=py311hca03da5_0
  - nbformat=5.9.2=py311hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=py311hca03da5_0
  - nettle=3.7.3=h84b5d62_1
  - networkx=3.1=py311hca03da5_0
  - ninja=1.10.2=hca03da5_5
  - ninja-base=1.10.2=h525c30c_5
  - notebook-shim=0.2.3=py311hca03da5_0
  - numexpr=2.8.7=py311h6dc990b_0
  - numpy=1.26.4=py311he598dae_0
  - numpy-base=1.26.4=py311hfbfe69c_0
  - opencv=4.6.0=py311hbae66a1_5
  - openh264=1.8.0=h98b2900_0
  - openjpeg=2.3.0=h7a6adac_2
  - openpyxl=3.0.10=py311h80987f9_0
  - openssl=3.5.4=h5503f6c_0
  - optuna=4.5.0=pyhd8ed1ab_0
  - overrides=7.4.0=py311hca03da5_0
  - packaging=23.2=py311hca03da5_0
  - pandas=2.1.4=py311h7aedaa7_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - patsy=0.5.3=py311hca03da5_0
  - pcre2=10.42=hb066dcc_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=10.3.0=py311h80987f9_0
  - pixman=0.40.0=h1a28f6b_0
  - platformdirs=3.10.0=py311hca03da5_0
  - plotly=5.19.0=py311hb6e6a13_0
  - prometheus_client=0.14.1=py311hca03da5_0
  - prompt-toolkit=3.0.43=py311hca03da5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py311h80987f9_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py311hca03da5_1
  - pyparsing=3.0.9=py311hca03da5_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.5=hb885b13_0
  - python-dateutil=2.9.0post0=py311hca03da5_2
  - python-fastjsonschema=2.16.2=py311hca03da5_0
  - python-json-logger=2.0.7=py311hca03da5_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytorch=2.2.0=gpu_mps_py311hf322ab5_100
  - pytz=2024.1=py311hca03da5_0
  - pyyaml=6.0.1=py311h80987f9_0
  - pyzmq=25.1.2=py311h313beb8_0
  - qt-main=5.15.2=h9b4df51_9
  - qt-webengine=5.15.9=h2903aaf_7
  - qtwebkit=5.212=h19f419d_5
  - readline=8.2=h1a28f6b_0
  - referencing=0.30.2=py311hca03da5_0
  - requests=2.32.2=py311hca03da5_0
  - rfc3339-validator=0.1.4=py311hca03da5_0
  - rfc3986-validator=0.1.1=py311hca03da5_0
  - rpds-py=0.10.6=py311hf0e4da2_0
  - scikit-image=0.22.0=py311h7aedaa7_0
  - scipy=1.11.4=py311hc76d9b0_0
  - send2trash=1.8.2=py311hca03da5_0
  - setuptools=69.5.1=py311hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sleef=3.5.1=h80987f9_2
  - snappy=1.1.10=h313beb8_1
  - sniffio=1.3.0=py311hca03da5_0
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - soupsieve=2.5=py311hca03da5_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sqlalchemy=2.0.43=py311h9945a3e_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.0=py311hb9f6ed7_0
  - sympy=1.12=py311hca03da5_0
  - tenacity=8.2.2=py311hca03da5_0
  - terminado=0.17.1=py311hca03da5_0
  - tifffile=2023.4.12=py311hca03da5_0
  - tinycss2=1.2.1=py311hca03da5_0
  - tk=8.6.14=h6ba3021_0
  - tornado=6.3.3=py311h80987f9_0
  - tqdm=4.65.0=py311hb6e6a13_0
  - typing-extensions=4.11.0=py311hca03da5_0
  - typing_extensions=4.11.0=py311hca03da5_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py311h80987f9_0
  - urllib3=2.2.1=py311hca03da5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311hca03da5_1
  - websocket-client=1.8.0=py311hca03da5_0
  - wheel=0.43.0=py311hca03da5_0
  - x264=1!152.20180806=h1a28f6b_0
  - xz=5.4.6=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h313beb8_0
  - zfp=1.0.0=h313beb8_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h18a0788_1
  - zstd=1.5.5=hd90d995_2
  - pip:
      - alabaster==0.7.16
      - arrow==1.3.0
      - botorch==0.10.0
      - cloudpickle==3.0.0
      - contrastive==1.2.0
      - fqdn==1.5.1
      - gpytorch==1.11
      - h11==0.14.0
      - hf-xet==1.1.2
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.32.3
      - ipympl==0.9.4
      - ipython==8.24.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - jaxtyping==0.2.25
      - jsonpointer==2.4
      - jupyter==1.0.0
      - jupyter-console==6.6.3
      - jupyterlab==4.2.1
      - jupyterlab-server==2.27.2
      - jupyterlab-widgets==3.0.10
      - linear-operator==0.5.1
      - llvmlite==0.43.0
      - matplotlib==3.9.0
      - multipledispatch==1.0.0
      - notebook==7.2.0
      - numba==0.60.0
      - numpydoc==1.7.0
      - opt-einsum==3.3.0
      - pip==24.0
      - pot==0.9.3
      - pynndescent==0.5.13
      - pyro-api==0.1.2
      - pyro-ppl==1.9.0
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - rdkit==2023.9.5
      - regex==2024.11.6
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - seaborn==0.13.2
      - shap==0.46.0
      - slicer==0.0.8
      - sphinx==7.3.7
      - sphinx-rtd-theme==2.0.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-serializinghtml==1.1.10
      - tabulate==0.9.0
      - threadpoolctl==3.6.0
      - tokenizers==0.21.1
      - torcheval==0.0.7
      - traitlets==5.14.3
      - transformers==4.52.4
      - typeguard==2.13.3
      - types-python-dateutil==2.9.0.20240316
      - umap-learn==0.5.6
      - uri-template==1.3.0
      - vendi-score==0.0.3
      - webcolors==1.13
      - widgetsnbextension==4.0.10
      - xgboost==2.1.1

