name: smi-ted
channels:
  - defaults
dependencies:
  - _tflow_select=2.2.0=eigen
  - abseil-cpp=20211102.0=hc377ac9_0
  - absl-py=2.1.0=py39hca03da5_0
  - anyio=4.6.2=py39hca03da5_0
  - appnope=0.1.2=py39hca03da5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h80987f9_1
  - asttokens=3.0.0=py39hca03da5_0
  - astunparse=1.6.3=py_0
  - async-lru=2.0.4=py39hca03da5_0
  - async-timeout=5.0.1=py39hca03da5_0
  - babel=2.16.0=py39hca03da5_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.3=py39hca03da5_0
  - blas=1.0=openblas
  - bleach=6.2.0=py39hca03da5_0
  - blinker=1.9.0=py39hca03da5_0
  - brotli-python=1.0.9=py39h313beb8_9
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2025.7.15=hca03da5_0
  - cachetools=5.5.1=py39hca03da5_0
  - certifi=2025.8.3=py39hca03da5_0
  - cffi=1.17.1=py39h3eb5a62_1
  - click=8.1.8=py39hca03da5_0
  - comm=0.2.1=py39hca03da5_0
  - cryptography=41.0.3=py39h3c57c4d_0
  - debugpy=1.8.11=py39h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.2.0=py39hca03da5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.4=h313beb8_0
  - flatbuffers=24.3.25=h313beb8_0
  - frozenlist=1.5.0=py39h80987f9_0
  - gast=0.4.0=pyhd3eb1b0_0
  - giflib=5.2.2=h80987f9_0
  - google-auth=2.38.0=py39hca03da5_1
  - google-auth-oauthlib=0.5.2=py39hca03da5_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpc-cpp=1.48.2=h877324c_0
  - grpcio=1.48.2=py39h877324c_0
  - h11=0.14.0=py39hca03da5_0
  - h5py=3.12.1=py39h8456320_0
  - hdf5=1.12.1=h160e8cb_2
  - httpcore=1.0.2=py39hca03da5_0
  - httpx=0.27.0=py39hca03da5_0
  - icu=68.1=hc377ac9_0
  - importlib-metadata=8.5.0=py39hca03da5_0
  - importlib_metadata=8.5.0=hd3eb1b0_0
  - ipykernel=6.29.5=py39hca03da5_1
  - ipython=8.15.0=py39hca03da5_0
  - ipywidgets=8.1.5=py39hca03da5_0
  - jedi=0.19.2=py39hca03da5_0
  - jinja2=3.1.6=py39hca03da5_0
  - jpeg=9e=h80987f9_3
  - json5=0.9.25=py39hca03da5_0
  - jsonschema=4.23.0=py39hca03da5_0
  - jsonschema-specifications=2023.7.1=py39hca03da5_0
  - jupyter-lsp=2.2.0=py39hca03da5_0
  - jupyter_client=8.6.3=py39hca03da5_0
  - jupyter_core=5.7.2=py39hca03da5_0
  - jupyter_events=0.12.0=py39hca03da5_0
  - jupyter_server=2.15.0=py39hca03da5_0
  - jupyter_server_terminals=0.4.4=py39hca03da5_1
  - jupyterlab=4.3.4=py39hca03da5_0
  - jupyterlab_pygments=0.3.0=py39hca03da5_0
  - jupyterlab_server=2.27.3=py39hca03da5_0
  - jupyterlab_widgets=3.0.13=py39hca03da5_0
  - keras=2.12.0=py39hca03da5_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - krb5=1.20.1=h8380606_1
  - libcurl=8.2.1=h0f1d93c_0
  - libcxx=14.0.6=h848a8c0_0
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libiconv=1.16=h80987f9_3
  - libnghttp2=1.52.0=h10c0552_1
  - libopenblas=0.3.29=hea593b9_0
  - libpng=1.6.39=h80987f9_0
  - libprotobuf=3.20.3=h514c7bf_0
  - libsodium=1.0.18=h1a28f6b_0
  - libssh2=1.10.0=h449679c_2
  - llvm-openmp=14.0.6=hc6e5704_0
  - markdown=3.8=py39hca03da5_0
  - markupsafe=3.0.2=py39h80987f9_0
  - matplotlib-inline=0.1.6=py39hca03da5_0
  - mistune=3.1.2=py39hca03da5_0
  - narwhals=1.31.0=py39hca03da5_1
  - nbclient=0.10.2=py39hca03da5_0
  - nbconvert-core=7.16.6=py39hca03da5_0
  - nbformat=5.10.4=py39hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=py39hca03da5_0
  - notebook=7.3.2=py39hca03da5_0
  - notebook-shim=0.2.4=py39hca03da5_0
  - numpy-base=1.23.5=py39h90707a3_0
  - oauthlib=3.2.2=py39hca03da5_0
  - openssl=1.1.1w=h1a28f6b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - overrides=7.4.0=py39hca03da5_0
  - packaging=24.2=py39hca03da5_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=py39hca03da5_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=25.0=py39hca03da5_0
  - platformdirs=3.10.0=py39hca03da5_0
  - plotly=6.0.1=py39hd096484_0
  - prometheus_client=0.21.0=py39hca03da5_0
  - prompt-toolkit=3.0.43=py39hca03da5_0
  - propcache=0.3.1=py39h80987f9_0
  - protobuf=3.20.3=py39h313beb8_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py39hca03da5_1
  - pyjwt=2.10.1=py39hca03da5_0
  - pyopenssl=23.2.0=py39hca03da5_0
  - pysocks=1.7.1=py39hca03da5_0
  - python=3.9.7=hc70090a_1
  - python-dateutil=2.9.0post0=py39hca03da5_2
  - python-fastjsonschema=2.20.0=py39hca03da5_0
  - python-flatbuffers=24.3.25=py39hca03da5_0
  - python-json-logger=3.2.1=py39hca03da5_0
  - pyyaml=6.0.2=py39h80987f9_0
  - pyzmq=26.2.0=py39h313beb8_0
  - re2=2022.04.01=hc377ac9_0
  - readline=8.2=h1a28f6b_0
  - referencing=0.30.2=py39hca03da5_0
  - requests=2.32.3=py39hca03da5_1
  - requests-oauthlib=2.0.0=py39hca03da5_0
  - rfc3339-validator=0.1.4=py39hca03da5_0
  - rfc3986-validator=0.1.1=py39hca03da5_0
  - rpds-py=0.22.3=py39h2aea54e_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.13.1=py39hd336fd7_1
  - send2trash=1.8.2=py39hca03da5_1
  - setuptools=75.8.0=py39hca03da5_0
  - snappy=1.2.1=h313beb8_0
  - sniffio=1.3.0=py39hca03da5_0
  - soupsieve=2.5=py39hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tensorboard=2.12.1=py39hca03da5_0
  - tensorboard-data-server=0.7.0=py39ha6e5c4f_1
  - tensorboard-plugin-wit=1.8.1=py39hca03da5_0
  - tensorflow=2.12.0=eigen_py39h767e93f_0
  - tensorflow-base=2.12.0=eigen_py39h0a52ebb_0
  - tensorflow-estimator=2.12.0=py39hca03da5_0
  - termcolor=2.1.0=py39hca03da5_0
  - terminado=0.17.1=py39hca03da5_0
  - tinycss2=1.4.0=py39hca03da5_0
  - tk=8.6.14=h6ba3021_0
  - tomli=2.0.1=py39hca03da5_0
  - tornado=6.4.2=py39h80987f9_0
  - traitlets=5.14.3=py39hca03da5_0
  - typing_extensions=4.12.2=py39hca03da5_0
  - urllib3=2.3.0=py39hca03da5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39hca03da5_1
  - websocket-client=1.8.0=py39hca03da5_0
  - werkzeug=3.1.3=py39hca03da5_0
  - wheel=0.35.1=pyhd3eb1b0_0
  - widgetsnbextension=4.0.13=py39hca03da5_0
  - wrapt=1.17.0=py39h80987f9_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h313beb8_0
  - zipp=3.21.0=py39hca03da5_0
  - zlib=1.2.13=h18a0788_1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - attrs==25.3.0
      - charset-normalizer==3.4.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - datasets==3.5.0
      - dill==0.3.8
      - docstring-parser==0.16
      - evaluate==0.4.3
      - filelock==3.18.0
      - fonttools==4.57.0
      - fsspec==2024.12.0
      - huggingface-hub==0.30.1
      - idna==3.10
      - importlib-resources==6.5.2
      - joblib==1.4.2
      - jsonargparse==4.32.1
      - kiwisolver==1.4.7
      - lightning==2.5.1.post0
      - lightning-utilities==0.14.3
      - litgpt==0.5.8
      - llvmlite==0.43.0
      - matplotlib==3.9.2
      - mordred==1.2.0
      - mpmath==1.3.0
      - multidict==6.3.2
      - multiprocess==0.70.16
      - networkx==2.8.8
      - numba==0.60.0
      - numpy==1.26.4
      - pandas==2.2.3
      - pillow==11.1.0
      - psutil==7.0.0
      - pubchempy==1.0.4
      - pyarrow==19.0.1
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - pytorch-lightning==2.5.1.post0
      - pytorch-ranger==0.1.1
      - pytz==2025.2
      - rdkit==2024.9.6
      - regex==2024.11.6
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - seaborn==0.13.2
      - selfies==2.2.0
      - six==1.17.0
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - torch==2.6.0
      - torch-geometric==2.6.1
      - torch-optimizer==0.3.0
      - torchinfo==1.8.0
      - torchmetrics==1.7.2
      - tqdm==4.67.1
      - transformers==4.51.0
      - typeshed-client==2.7.0
      - typing-extensions==4.13.1
      - tzdata==2025.2
      - umap-learn==0.5.7
      - xgboost==1.6.2
      - xxhash==3.5.0
      - yarl==1.19.0
