name: VICGAE
channels:
  - defaults
dependencies:
  - anyio=4.10.0=py39hca03da5_0
  - appnope=0.1.4=py39hca03da5_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py39h254cc4a_0
  - asttokens=3.0.0=py39hca03da5_0
  - async-lru=2.0.4=py39hca03da5_0
  - attrs=24.3.0=py39hca03da5_0
  - babel=2.16.0=py39hca03da5_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.13.5=py39hca03da5_0
  - bleach=6.2.0=py39hca03da5_0
  - brotlicffi=1.0.9.2=py39h313beb8_1
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.9.9=hca03da5_0
  - certifi=2025.8.3=py39hca03da5_0
  - cffi=1.17.1=py39h3eb5a62_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.1=py39hca03da5_0
  - debugpy=1.8.16=py39h0962b89_0
  - decorator=5.2.1=py39hca03da5_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.2.0=py39hca03da5_0
  - executing=2.2.1=py39hca03da5_0
  - expat=2.7.1=h313beb8_0
  - h11=0.16.0=py39hca03da5_0
  - httpcore=1.0.9=py39hca03da5_0
  - httpx=0.28.1=py39hca03da5_0
  - idna=3.7=py39hca03da5_0
  - importlib-metadata=8.5.0=py39hca03da5_0
  - importlib_metadata=8.5.0=hd3eb1b0_0
  - ipykernel=6.30.1=py39hca03da5_0
  - ipython=8.15.0=py39hca03da5_0
  - jedi=0.19.2=py39hca03da5_0
  - jinja2=3.1.6=py39hca03da5_0
  - json5=0.9.25=py39hca03da5_0
  - jsonschema=4.25.0=py39hca03da5_0
  - jsonschema-specifications=2023.7.1=py39hca03da5_0
  - jupyter-lsp=2.2.5=py39hca03da5_0
  - jupyter_client=8.6.3=py39hca03da5_0
  - jupyter_core=5.8.1=py39hca03da5_0
  - jupyter_events=0.12.0=py39hca03da5_0
  - jupyter_server=2.16.0=py39hca03da5_0
  - jupyter_server_terminals=0.5.3=py39hca03da5_0
  - jupyterlab=4.4.7=py39hca03da5_0
  - jupyterlab_pygments=0.3.0=py39hca03da5_0
  - jupyterlab_server=2.27.3=py39hca03da5_0
  - libcxx=20.1.8=h8869778_0
  - libffi=3.4.4=hca03da5_1
  - libsodium=1.0.20=h897f8a9_0
  - libzlib=1.3.1=h5f15de7_0
  - markupsafe=3.0.2=py39h80987f9_0
  - matplotlib-inline=0.1.7=py39hca03da5_0
  - mistune=3.1.2=py39hca03da5_0
  - nbclient=0.10.2=py39hca03da5_0
  - nbconvert-core=7.16.6=py39hca03da5_0
  - nbformat=5.10.4=py39hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=py39hca03da5_0
  - notebook=7.4.5=py39hca03da5_0
  - notebook-shim=0.2.4=py39hca03da5_0
  - openssl=3.0.17=h4ee41c1_0
  - overrides=7.4.0=py39hca03da5_0
  - packaging=25.0=py39hca03da5_0
  - pandocfilters=1.5.1=py39hca03da5_0
  - parso=0.8.4=py39hca03da5_0
  - pexpect=4.9.0=py39hca03da5_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=25.2=pyhc872135_0
  - platformdirs=4.3.7=py39hca03da5_0
  - prometheus_client=0.21.1=py39hca03da5_0
  - prompt-toolkit=3.0.43=py39hca03da5_0
  - psutil=7.0.0=py39h254cc4a_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.3=py39hca03da5_0
  - pycparser=2.23=py39hca03da5_0
  - pygments=2.19.1=py39hca03da5_0
  - pysocks=1.7.1=py39hca03da5_0
  - python=3.9.23=h99c0cbc_0
  - python-dateutil=2.9.0post0=py39hca03da5_2
  - python-fastjsonschema=2.20.0=py39hca03da5_0
  - python-json-logger=3.2.1=py39hca03da5_0
  - pyyaml=6.0.2=py39h80987f9_0
  - pyzmq=27.1.0=py39h854a7ef_0
  - readline=8.3=h0b18652_0
  - referencing=0.30.2=py39hca03da5_0
  - requests=2.32.5=py39hca03da5_0
  - rfc3339-validator=0.1.4=py39hca03da5_0
  - rfc3986-validator=0.1.1=py39hca03da5_0
  - rpds-py=0.22.3=py39h2aea54e_0
  - send2trash=1.8.2=py39hca03da5_1
  - setuptools=78.1.1=py39hca03da5_0
  - six=1.17.0=py39hca03da5_0
  - sniffio=1.3.0=py39hca03da5_0
  - soupsieve=2.5=py39hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - stack_data=0.6.3=py39hca03da5_0
  - terminado=0.18.1=py39hca03da5_0
  - tinycss2=1.4.0=py39hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - tomli=2.2.1=py39hca03da5_0
  - tornado=6.5.1=py39h80987f9_0
  - traitlets=5.14.3=py39hca03da5_0
  - typing-extensions=4.15.0=py39hca03da5_0
  - typing_extensions=4.15.0=py39hca03da5_0
  - urllib3=2.5.0=py39hca03da5_0
  - wcwidth=0.2.13=py39hca03da5_0
  - webencodings=0.5.1=py39hca03da5_1
  - websocket-client=1.8.0=py39hca03da5_0
  - wheel=0.45.1=py39hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h2c7f8f0_1
  - zipp=3.21.0=py39hca03da5_0
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - astrochem-embedding==0.2.0
      - async-timeout==5.0.1
      - click==8.1.8
      - eval-type-backport==0.2.2
      - filelock==3.19.1
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - joblib==1.5.2
      - lightning-utilities==0.15.2
      - mpmath==1.3.0
      - multidict==6.6.4
      - networkx==3.2.1
      - numpy==2.0.2
      - palettable==3.3.3
      - pandas==2.3.3
      - pillow==11.3.0
      - propcache==0.3.2
      - protobuf==6.32.1
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pytorch-lightning==2.5.5
      - pytz==2025.2
      - rdkit-pypi==2022.9.5
      - ruamel-yaml==0.18.15
      - ruamel-yaml-clib==0.2.14
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - selfies==2.2.0
      - sentry-sdk==2.39.0
      - smmap==5.0.2
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.8.0
      - torchinfo==1.8.0
      - torchmetrics==1.8.2
      - tqdm==4.67.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - wandb==0.22.1
      - yarl==1.20.1
